apiVersion: apps/v1
kind: Deployment
metadata:
  name: svencoop-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: svencoop-server
  template:
    metadata:
      labels:
        app: svencoop-server
    spec:
      containers:
        - name: svends
          image: registry.bgsystems.home/marine789/svencoop-docker:20210928203609
          command:
            - ./svends_run
          args:
            - -console
            - -port 27015
            - +maxplayers 8
            - +log on
            - +map "stadium4"
          ports:
            - containerPort: 47170
              name: hlds-1
              protocol: UDP
            - containerPort: 27015
              name: hlds-2
              protocol: UDP
          resources:
            requests:
              memory: 1Gi
              cpu: 1000m
            limits:
              memory: 2Gi
              cpu: 2000m
          envFrom:
            - configMapRef:
                name: cm-svencoop-server
