apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "../../base"
  - ingress.yaml

namespace: svencoop-server
  
# MODIFICAR EL ARCHIVO './application.envs' PARA CONFIGURAR LAS VARIABLES DE ENTORNO
configMapGenerator:
- name: cm-svencoop-server
  envs:
  - application.envs