name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_REPO_USER: ${{ secrets.DOCKER_REPO_USER }}
    steps:
      - name: Get current time
        uses: 1466587594/get-current-time@v2
        id: current-time
        with:
          format: YYYYMMDDHHmmss
          utcOffset: "-03:00"
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_REPO_USER }}
          password: ${{ secrets.DOCKER_REPO_PASSWORD }}
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        run: docker build . --file Dockerfile --tag $DOCKER_REPO_USER/svencoop-docker:$F_TIME
      - uses: actions/checkout@v2
      - name: Push image into repo
        env:
            F_TIME: "${{ steps.current-time.outputs.formattedTime }}"
        run: docker push $DOCKER_REPO_USER/svencoop-docker:$F_TIME
